name: Python package

on:
  workflow_dispatch:
   inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
      version:
        description: 'Package version'
        required: true
        type: string
      body:
        description: 'Release body'
        required: true
        type: string
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
    - name: Update setup.cfg
      run: | 
        sed -i "s+version = 1.0+version = ${{ github.event.inputs.version }}+g" 'setup.cfg'
    - name: Build package
      run: |
        python -m build
    - name: Create release with distribution
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: '${{ github.event.inputs.tag }}'
        files: ./dist/*
        body: '${{ github.event.inputs.body }}'
